/* This is auto-generated code from LDmicro. Do not edit this file! Go
   back to the ladder diagram source for changes in the logic, and make
   any C additions either in ladder.h or in additional .c files linked
   against this one. */

/* You must provide ladder.h; there you must provide:
      * a typedef for SWORD and BOOL, signed 16 bit and boolean types
        (probably typedef signed short SWORD; typedef unsigned char BOOL;)

   You must also provide implementations of all the I/O read/write
   either as inlines in the header file or in another source file. (The
   I/O functions are all declared extern.)

   See the generated source code (below) for function names. */
#include "ladder.h"

/* Define EXTERN_EVERYTHING in ladder.h if you want all symbols extern.
   This could be useful to implement `magic variables,' so that for
   example when you write to the ladder variable duty_cycle, your PLC
   runtime can look at the C variable U_duty_cycle and use that to set
   the PWM duty cycle on the micro. That way you can add support for
   peripherals that LDmicro doesn't know about. */
#ifdef EXTERN_EVERYTHING
#define STATIC 
#else
#define STATIC static
#endif

/* Define NO_PROTOTYPES if you don't want LDmicro to provide prototypes for
   all the I/O functions (Read_U_xxx, Write_U_xxx) that you must provide.
   If you define this then you must provide your own prototypes for these
   functions in ladder.h, or provide definitions (e.g. as inlines or macros)
   for them in ladder.h. */
#ifdef NO_PROTOTYPES
#define PROTO(x)
#else
#define PROTO(x) x
#endif

/* U_xxx symbols correspond to user-defined names. There is such a symbol
   for every internal relay, variable, timer, and so on in the ladder
   program. I_xxx symbols are internally generated. */
STATIC BOOL I_b_mcr = 0;
#define Read_I_b_mcr() I_b_mcr
#define Write_I_b_mcr(x) I_b_mcr = x
STATIC BOOL I_b_rung_top = 0;
#define Read_I_b_rung_top() I_b_rung_top
#define Write_I_b_rung_top(x) I_b_rung_top = x
STATIC BOOL I_b_parOut_0000 = 0;
#define Read_I_b_parOut_0000() I_b_parOut_0000
#define Write_I_b_parOut_0000(x) I_b_parOut_0000 = x
STATIC BOOL I_b_parThis_0000 = 0;
#define Read_I_b_parThis_0000() I_b_parThis_0000
#define Write_I_b_parThis_0000(x) I_b_parThis_0000 = x

/* You provide this function. */
PROTO(extern BOOL Read_U_b_XStart(void);)

STATIC BOOL U_b_RMaster = 0;
#define Read_U_b_RMaster() U_b_RMaster
#define Write_U_b_RMaster(x) U_b_RMaster = x

/* You provide this function. */
PROTO(extern BOOL Read_U_b_XStop(void);)

STATIC BOOL I_b_parOut_0001 = 0;
#define Read_I_b_parOut_0001() I_b_parOut_0001
#define Write_I_b_parOut_0001(x) I_b_parOut_0001 = x
STATIC BOOL I_b_parThis_0001 = 0;
#define Read_I_b_parThis_0001() I_b_parThis_0001
#define Write_I_b_parThis_0001(x) I_b_parThis_0001 = x

/* You provide this function. */
PROTO(extern BOOL Read_U_b_XBottle_IN(void);)

STATIC BOOL U_b_RBottle_HOLD = 0;
#define Read_U_b_RBottle_HOLD() U_b_RBottle_HOLD
#define Write_U_b_RBottle_HOLD(x) U_b_RBottle_HOLD = x
STATIC BOOL U_b_RBottle_RELEASE = 0;
#define Read_U_b_RBottle_RELEASE() U_b_RBottle_RELEASE
#define Write_U_b_RBottle_RELEASE(x) U_b_RBottle_RELEASE = x
STATIC BOOL I_b_parOut_0002 = 0;
#define Read_I_b_parOut_0002() I_b_parOut_0002
#define Write_I_b_parOut_0002(x) I_b_parOut_0002 = x
STATIC BOOL I_b_parThis_0002 = 0;
#define Read_I_b_parThis_0002() I_b_parThis_0002
#define Write_I_b_parThis_0002(x) I_b_parThis_0002 = x

/* You provide these functions. */
PROTO(BOOL Read_U_b_YBottle_HOLD(void);)
PROTO(void Write_U_b_YBottle_HOLD(BOOL v);)

STATIC SWORD U_i_T0 = 0;
STATIC BOOL U_b_RHOLD_DN = 0;
#define Read_U_b_RHOLD_DN() U_b_RHOLD_DN
#define Write_U_b_RHOLD_DN(x) U_b_RHOLD_DN = x
STATIC BOOL U_b_RWater_ON = 0;
#define Read_U_b_RWater_ON() U_b_RWater_ON
#define Write_U_b_RWater_ON(x) U_b_RWater_ON = x
STATIC BOOL U_b_RMotor_REVERSE = 0;
#define Read_U_b_RMotor_REVERSE() U_b_RMotor_REVERSE
#define Write_U_b_RMotor_REVERSE(x) U_b_RMotor_REVERSE = x
STATIC BOOL I_b_parOut_0003 = 0;
#define Read_I_b_parOut_0003() I_b_parOut_0003
#define Write_I_b_parOut_0003(x) I_b_parOut_0003 = x
STATIC BOOL I_b_parThis_0003 = 0;
#define Read_I_b_parThis_0003() I_b_parThis_0003
#define Write_I_b_parThis_0003(x) I_b_parThis_0003 = x

/* You provide these functions. */
PROTO(BOOL Read_U_b_YMotor_FORWARD(void);)
PROTO(void Write_U_b_YMotor_FORWARD(BOOL v);)

STATIC BOOL U_b_RMotor_FORWARD = 0;
#define Read_U_b_RMotor_FORWARD() U_b_RMotor_FORWARD
#define Write_U_b_RMotor_FORWARD(x) U_b_RMotor_FORWARD = x
STATIC BOOL I_b_parOut_0004 = 0;
#define Read_I_b_parOut_0004() I_b_parOut_0004
#define Write_I_b_parOut_0004(x) I_b_parOut_0004 = x
STATIC BOOL I_b_parThis_0004 = 0;
#define Read_I_b_parThis_0004() I_b_parThis_0004
#define Write_I_b_parThis_0004(x) I_b_parThis_0004 = x

/* You provide this function. */
PROTO(extern BOOL Read_U_b_XPosition_DOWN(void);)

STATIC BOOL U_b_RWater_OFF = 0;
#define Read_U_b_RWater_OFF() U_b_RWater_OFF
#define Write_U_b_RWater_OFF(x) U_b_RWater_OFF = x
STATIC BOOL I_b_parOut_0005 = 0;
#define Read_I_b_parOut_0005() I_b_parOut_0005
#define Write_I_b_parOut_0005(x) I_b_parOut_0005 = x
STATIC BOOL I_b_parThis_0005 = 0;
#define Read_I_b_parThis_0005() I_b_parThis_0005
#define Write_I_b_parThis_0005(x) I_b_parThis_0005 = x

/* You provide these functions. */
PROTO(BOOL Read_U_b_YWater_ON(void);)
PROTO(void Write_U_b_YWater_ON(BOOL v);)

STATIC SWORD U_i_T1 = 0;
STATIC BOOL I_b_parOut_0006 = 0;
#define Read_I_b_parOut_0006() I_b_parOut_0006
#define Write_I_b_parOut_0006(x) I_b_parOut_0006 = x
STATIC BOOL I_b_parThis_0006 = 0;
#define Read_I_b_parThis_0006() I_b_parThis_0006
#define Write_I_b_parThis_0006(x) I_b_parThis_0006 = x

/* You provide this function. */
PROTO(extern BOOL Read_U_b_XBottle_UP(void);)

STATIC BOOL I_b_parOut_0007 = 0;
#define Read_I_b_parOut_0007() I_b_parOut_0007
#define Write_I_b_parOut_0007(x) I_b_parOut_0007 = x
STATIC BOOL I_b_parThis_0007 = 0;
#define Read_I_b_parThis_0007() I_b_parThis_0007
#define Write_I_b_parThis_0007(x) I_b_parThis_0007 = x

/* You provide these functions. */
PROTO(BOOL Read_U_b_YMotor_REVERSE(void);)
PROTO(void Write_U_b_YMotor_REVERSE(BOOL v);)

STATIC BOOL I_b_parOut_0008 = 0;
#define Read_I_b_parOut_0008() I_b_parOut_0008
#define Write_I_b_parOut_0008(x) I_b_parOut_0008 = x
STATIC BOOL I_b_parThis_0008 = 0;
#define Read_I_b_parThis_0008() I_b_parThis_0008
#define Write_I_b_parThis_0008(x) I_b_parThis_0008 = x
STATIC SWORD U_i_T2 = 0;
STATIC BOOL I_b_parOut_0009 = 0;
#define Read_I_b_parOut_0009() I_b_parOut_0009
#define Write_I_b_parOut_0009(x) I_b_parOut_0009 = x
STATIC BOOL I_b_parThis_0009 = 0;
#define Read_I_b_parThis_0009() I_b_parThis_0009
#define Write_I_b_parThis_0009(x) I_b_parThis_0009 = x

/* You provide these functions. */
PROTO(BOOL Read_U_b_YBottle_RELEASE(void);)
PROTO(void Write_U_b_YBottle_RELEASE(BOOL v);)



/* Call this function once per PLC cycle. You are responsible for calling
   it at the interval that you specified in the MCU configuration when you
   generated this code. */
void PlcCycle(void)
{
    Write_I_b_mcr(1);
    
    /* start rung 1 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    /* start parallel [ */
    Write_I_b_parOut_0000(0);
    Write_I_b_parThis_0000(Read_I_b_rung_top());
    if(!Read_U_b_XStart()) {
        Write_I_b_parThis_0000(0);
    }
    
    if(Read_I_b_parThis_0000()) {
        Write_I_b_parOut_0000(1);
    }
    Write_I_b_parThis_0000(Read_I_b_rung_top());
    if(!Read_U_b_RMaster()) {
        Write_I_b_parThis_0000(0);
    }
    
    if(Read_I_b_parThis_0000()) {
        Write_I_b_parOut_0000(1);
    }
    Write_I_b_rung_top(Read_I_b_parOut_0000());
    /* ] finish parallel */
    if(Read_U_b_XStop()) {
        Write_I_b_rung_top(0);
    }
    
    Write_U_b_RMaster(Read_I_b_rung_top());
    
    /* ] finish series */
    
    /* start rung 2 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(!Read_U_b_RMaster()) {
        Write_I_b_rung_top(0);
    }
    
    /* start parallel [ */
    Write_I_b_parOut_0001(0);
    Write_I_b_parThis_0001(Read_I_b_rung_top());
    if(!Read_U_b_XBottle_IN()) {
        Write_I_b_parThis_0001(0);
    }
    
    if(Read_I_b_parThis_0001()) {
        Write_I_b_parOut_0001(1);
    }
    Write_I_b_parThis_0001(Read_I_b_rung_top());
    if(!Read_U_b_RBottle_HOLD()) {
        Write_I_b_parThis_0001(0);
    }
    
    if(Read_I_b_parThis_0001()) {
        Write_I_b_parOut_0001(1);
    }
    Write_I_b_rung_top(Read_I_b_parOut_0001());
    /* ] finish parallel */
    if(Read_U_b_RBottle_RELEASE()) {
        Write_I_b_rung_top(0);
    }
    
    /* start parallel [ */
    Write_I_b_parOut_0002(0);
    Write_I_b_parThis_0002(Read_I_b_rung_top());
    Write_U_b_YBottle_HOLD(Read_I_b_parThis_0002());
    
    if(Read_I_b_parThis_0002()) {
        Write_I_b_parOut_0002(1);
    }
    Write_I_b_parThis_0002(Read_I_b_rung_top());
    Write_U_b_RBottle_HOLD(Read_I_b_parThis_0002());
    
    if(Read_I_b_parThis_0002()) {
        Write_I_b_parOut_0002(1);
    }
    Write_I_b_rung_top(Read_I_b_parOut_0002());
    /* ] finish parallel */
    /* ] finish series */
    
    /* start rung 3 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(!Read_U_b_RMaster()) {
        Write_I_b_rung_top(0);
    }
    
    if(!Read_U_b_RBottle_HOLD()) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_I_b_rung_top()) {
        if(U_i_T0 < 99) {
            U_i_T0++;
            Write_I_b_rung_top(0);
        }
    } else {
        U_i_T0 = 0;
    }
    
    Write_U_b_RHOLD_DN(Read_I_b_rung_top());
    
    /* ] finish series */
    
    /* start rung 4 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(!Read_U_b_RMaster()) {
        Write_I_b_rung_top(0);
    }
    
    if(!Read_U_b_RHOLD_DN()) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_U_b_RWater_ON()) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_U_b_RMotor_REVERSE()) {
        Write_I_b_rung_top(0);
    }
    
    /* start parallel [ */
    Write_I_b_parOut_0003(0);
    Write_I_b_parThis_0003(Read_I_b_rung_top());
    Write_U_b_YMotor_FORWARD(Read_I_b_parThis_0003());
    
    if(Read_I_b_parThis_0003()) {
        Write_I_b_parOut_0003(1);
    }
    Write_I_b_parThis_0003(Read_I_b_rung_top());
    Write_U_b_RMotor_FORWARD(Read_I_b_parThis_0003());
    
    if(Read_I_b_parThis_0003()) {
        Write_I_b_parOut_0003(1);
    }
    Write_I_b_rung_top(Read_I_b_parOut_0003());
    /* ] finish parallel */
    /* ] finish series */
    
    /* start rung 5 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(!Read_U_b_RMaster()) {
        Write_I_b_rung_top(0);
    }
    
    /* start parallel [ */
    Write_I_b_parOut_0004(0);
    Write_I_b_parThis_0004(Read_I_b_rung_top());
    if(!Read_U_b_XPosition_DOWN()) {
        Write_I_b_parThis_0004(0);
    }
    
    if(Read_I_b_parThis_0004()) {
        Write_I_b_parOut_0004(1);
    }
    Write_I_b_parThis_0004(Read_I_b_rung_top());
    if(!Read_U_b_RWater_ON()) {
        Write_I_b_parThis_0004(0);
    }
    
    if(Read_I_b_parThis_0004()) {
        Write_I_b_parOut_0004(1);
    }
    Write_I_b_rung_top(Read_I_b_parOut_0004());
    /* ] finish parallel */
    if(Read_U_b_RWater_OFF()) {
        Write_I_b_rung_top(0);
    }
    
    /* start parallel [ */
    Write_I_b_parOut_0005(0);
    Write_I_b_parThis_0005(Read_I_b_rung_top());
    Write_U_b_YWater_ON(Read_I_b_parThis_0005());
    
    if(Read_I_b_parThis_0005()) {
        Write_I_b_parOut_0005(1);
    }
    Write_I_b_parThis_0005(Read_I_b_rung_top());
    Write_U_b_RWater_ON(Read_I_b_parThis_0005());
    
    if(Read_I_b_parThis_0005()) {
        Write_I_b_parOut_0005(1);
    }
    Write_I_b_rung_top(Read_I_b_parOut_0005());
    /* ] finish parallel */
    /* ] finish series */
    
    /* start rung 6 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(!Read_U_b_RMaster()) {
        Write_I_b_rung_top(0);
    }
    
    if(!Read_U_b_RWater_ON()) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_I_b_rung_top()) {
        if(U_i_T1 < 499) {
            U_i_T1++;
            Write_I_b_rung_top(0);
        }
    } else {
        U_i_T1 = 0;
    }
    
    Write_U_b_RWater_OFF(Read_I_b_rung_top());
    
    /* ] finish series */
    
    /* start rung 7 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(!Read_U_b_RMaster()) {
        Write_I_b_rung_top(0);
    }
    
    /* start parallel [ */
    Write_I_b_parOut_0006(0);
    Write_I_b_parThis_0006(Read_I_b_rung_top());
    if(!Read_U_b_RWater_OFF()) {
        Write_I_b_parThis_0006(0);
    }
    
    if(Read_I_b_parThis_0006()) {
        Write_I_b_parOut_0006(1);
    }
    Write_I_b_parThis_0006(Read_I_b_rung_top());
    if(!Read_U_b_RMotor_REVERSE()) {
        Write_I_b_parThis_0006(0);
    }
    
    if(Read_I_b_parThis_0006()) {
        Write_I_b_parOut_0006(1);
    }
    Write_I_b_rung_top(Read_I_b_parOut_0006());
    /* ] finish parallel */
    if(Read_U_b_XBottle_UP()) {
        Write_I_b_rung_top(0);
    }
    
    /* start parallel [ */
    Write_I_b_parOut_0007(0);
    Write_I_b_parThis_0007(Read_I_b_rung_top());
    Write_U_b_YMotor_REVERSE(Read_I_b_parThis_0007());
    
    if(Read_I_b_parThis_0007()) {
        Write_I_b_parOut_0007(1);
    }
    Write_I_b_parThis_0007(Read_I_b_rung_top());
    Write_U_b_RMotor_REVERSE(Read_I_b_parThis_0007());
    
    if(Read_I_b_parThis_0007()) {
        Write_I_b_parOut_0007(1);
    }
    Write_I_b_rung_top(Read_I_b_parOut_0007());
    /* ] finish parallel */
    /* ] finish series */
    
    /* start rung 8 */
    Write_I_b_rung_top(Read_I_b_mcr());
    
    /* start series [ */
    if(!Read_U_b_RMaster()) {
        Write_I_b_rung_top(0);
    }
    
    /* start parallel [ */
    Write_I_b_parOut_0008(0);
    Write_I_b_parThis_0008(Read_I_b_rung_top());
    if(!Read_U_b_XBottle_UP()) {
        Write_I_b_parThis_0008(0);
    }
    
    if(Read_I_b_parThis_0008()) {
        Write_I_b_parOut_0008(1);
    }
    Write_I_b_parThis_0008(Read_I_b_rung_top());
    if(!Read_U_b_RBottle_RELEASE()) {
        Write_I_b_parThis_0008(0);
    }
    
    if(Read_I_b_parThis_0008()) {
        Write_I_b_parOut_0008(1);
    }
    Write_I_b_rung_top(Read_I_b_parOut_0008());
    /* ] finish parallel */
    if(Read_U_b_XBottle_IN()) {
        Write_I_b_rung_top(0);
    }
    
    if(Read_I_b_rung_top()) {
        if(U_i_T2 < 99) {
            U_i_T2++;
            Write_I_b_rung_top(0);
        }
    } else {
        U_i_T2 = 0;
    }
    
    /* start parallel [ */
    Write_I_b_parOut_0009(0);
    Write_I_b_parThis_0009(Read_I_b_rung_top());
    Write_U_b_YBottle_RELEASE(Read_I_b_parThis_0009());
    
    if(Read_I_b_parThis_0009()) {
        Write_I_b_parOut_0009(1);
    }
    Write_I_b_parThis_0009(Read_I_b_rung_top());
    Write_U_b_RBottle_RELEASE(Read_I_b_parThis_0009());
    
    if(Read_I_b_parThis_0009()) {
        Write_I_b_parOut_0009(1);
    }
    Write_I_b_rung_top(Read_I_b_parOut_0009());
    /* ] finish parallel */
    /* ] finish series */
}
